version: "3.2"
services:
  postgres:
    image: postgres:10.6
    container_name: postgres-vulcan2x
    command: ["postgres", "-c", "log_min_duration_statement=1000"]
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=database
    ports:
      - "5437:5432"
